### ISSUE TITLE
Tech Sharing标签点了以后是404

### ISSUE THREAD

**Issue by txdywy** [papaya-mobile/papaya-tech-sharing#1]
希望尽快修复哦！

**Comment by cutewalker** [comment]
应该是在生成静态文件时，没有 git submodule update 之类， tech sharing 的内容没有拉到本地

**Comment by txdywy** [comment]
@chnak

**Comment by cutewalker** [comment]
更新了一下文档： https://github.com/papaya-mobile/papaya-mobile.github.io/commit/ea7568485255abcc7f512fc42a20dfaf807c1990

**Comment by chnak** [comment]
fixed
